apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.preempt_k8s.general.name }}
  namespace: {{ .Values.preempt_k8s.general.namespace }}
  labels:
    app: {{ .Values.preempt_k8s.general.name }}
data:
  MIN_WATCHDOGS: "{{ .Values.preempt_k8s.configMap.MIN_WATCHDOGS }}"
  MAX_WATCHDOGS: "{{ .Values.preempt_k8s.configMap.MAX_WATCHDOGS }}"
  THRESHOLD: "{{ .Values.preempt_k8s.configMap.THRESHOLD }}"
  EVENT_QUEUE: "{{ .Values.preempt_k8s.configMap.EVENT_QUEUE }}"
  THREAD_CPU_PINNING: "{{ .Values.preempt_k8s.configMap.THREAD_CPU_PINNING }}"
  RESOURCE_WATCHER_CPU_LIST: "{{ .Values.preempt_k8s.configMap.RESOURCE_WATCHER_CPU_LIST }}"
  POD_WATCHER_CPU_LIST: "{{ .Values.preempt_k8s.configMap.POD_WATCHER_CPU_LIST }}"
  SERVER_CPU_LIST: "{{ .Values.preempt_k8s.configMap.SERVER_CPU_LIST }}"
  STATE_UPDATER_CPU_LIST: "{{ .Values.preempt_k8s.configMap.STATE_UPDATER_CPU_LIST }}"
  WATCHDOGS_CPU_LIST: "{{ .Values.preempt_k8s.configMap.WATCHDOGS_CPU_LIST }}"
