apiVersion: v2
name: Preempt-K8s
version: 1.0.0
description: A Helm Chart for a Real-Time Kubernetes Controller that manages critical applications.
type: application
keywords:
  - kubernetes
  - real-time
  - criticality
  - priority
  - controller
  - preemptive
  - rtresource
home: https://github.com/dessertlab/preempt-k8s
sources:
  - https://github.com/dessertlab/preempt-k8s/controller
maintainers:
  - name: Stefano Toscano
    email: stefano.toscano@phd.unipd.it
  - name: Luigi De Simone
    email: luigi.desimone@unina.it
appVersion: "1.0.0"
