preempt_k8s:
  general:
    name: preempt-k8s
    namespace: realtime
  pod:
    restartPolicy: Always
    resources:
      limits:
        cpu: "2"
        memory: "3Gi"
      requests:
        cpu: "2"
        memory: "2Gi"
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      allowPrivilegeEscalation: true
      privileged: true
      readOnlyRootFilesystem: false
      capabilities:
        add:
          - SYS_NICE
          - IPC_OWNER
          - SYS_ADMIN
          - MKNOD
          - SYS_RESOURCE
    container:
      name: preempt-k8s-controller
      image:
        repository: dessertunina/preempt-k8s-cpu-pinned
        tag: 1.0.0
        pullPolicy: Always
      port: 80
  configMap:
    MIN_WATCHDOGS: "10"
    MAX_WATCHDOGS: "20"
    THRESHOLD: "3"
    EVENT_QUEUE: "/eventqueue"
    THREAD_CPU_PINNING: "true"
    RESOURCE_WATCHER_CPU_LIST: "0"
    POD_WATCHER_CPU_LIST: "1"
    SERVER_CPU_LIST: "2"
    STATE_UPDATER_CPU_LIST: "3"
    WATCHDOGS_CPU_LIST: "4,5"
  