apiVersion: v1
kind: ConfigMap
metadata:
  name: preempt-k8s
  namespace: realtime
  labels:
    app: preempt-k8s
data:
  MIN_WATCHDOGS: "10"
  MAX_WATCHDOGS: "20"
  THRESHOLD: "3"
  EVENT_QUEUE: "/eventqueue"
  THREAD_CPU_PINNING: "true"
  RESOURCE_WATCHER_CPU_LIST: "0"
  POD_WATCHER_CPU_LIST: "1"
  SERVER_CPU_LIST: "2"
  STATE_UPDATER_CPU_LIST: "3"
  WATCHDOGS_CPU_LIST: "4,5"
